# Generated by Django 5.0.2 on 2024-03-01 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspecciones', '0010_alter_fotorespuesta_respuesta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizacion',
            name='caracteristicas',
            field=models.CharField(blank=True, choices=[('reparaciones', 'Reparaciones'), ('planeacion', 'Planeacion')], max_length=20),
        ),
    ]
