# Generated by Django 5.0.6 on 2024-05-13 00:57

import multiselectfield.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inspecciones', '0011_alter_organizacion_caracteristicas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizacion',
            name='caracteristicas',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('reparaciones', 'Reparaciones'), ('planeacion', 'Planeacion')], max_length=20),
        ),
    ]
